FROM tanchihpin0517/picogen2:latest

ARG HOME="/home/picogen2"
ARG APP_PATH="$HOME/picogen2"
ARG DOCKER_USER="picogen2"

SHELL ["/bin/bash", "-c"]

WORKDIR ${APP_PATH}

COPY --chown=${DOCKER_USER} docker_temp/.piano_transcription_inference_data $HOME/.piano_transcription_inference_data
COPY --chown=${DOCKER_USER} docker_temp/.mirtoolkit $HOME/.mirtoolkit
COPY --chown=${DOCKER_USER} docker_temp/picogen2 $HOME/.cache/picogen2
COPY --chown=${DOCKER_USER} docker_temp/jukebox $HOME/.cache/jukebox
COPY --chown=${DOCKER_USER} docker_temp/sheetsage $HOME/.sheetsage/sheetsage
RUN mkdir -p $HOME/.cache/torch/hub/checkpoints
COPY --chown=${DOCKER_USER} docker_temp/beat_this-final0.ckpt $HOME/.cache/torch/hub/checkpoints/beat_this-final0.ckpt

ENTRYPOINT [ "bash", "-c" ]